apiVersion: v1
kind: Service
metadata:
  name: observability-service
  labels:
    app: observability-app
spec:
  type: NodePort
  selector:
    app: observability-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30007
